#!/usr/bin/env bash

###############################################
#                                             #
# Name:     Corona - positive people analyzer #
# Author:   Adam Ližičiar, xlizic00           #
#                                             #
###############################################

#arrays
ages=( 0 0 0 0 0 0 0 0 0 0 0 0 ) # store ages of people
genders=( 0 0 0 ) # man, woman, none

#variables
declare -i count=1
date=""

#colors
RED="\033[0;31m"
NOCOLOR="\033[0m"

################################################
############### HELP FUNCTIONS #################
################################################

filter_a() { 
    if [ "$1" != "1" ]
    then
        if [ "$2" == "-a" ] # data after date
        then
            if [[ "$3" > "$4" ]]
            then
                echo "1"
                return
            fi
        fi
    fi

    echo "0"
}
filter_b() { 
    if [ "$1" != "1" ]
    then
        if [ "$2" == "-a" ] # data after date
        then
            if [[ "$3" < "$4" ]]
            then
                echo "1"
                return
            fi
        fi
    fi

    echo "0"
}
filter_g() {
    if [ "$1" != "1" ]
    then
        if [ "$2" == "-g" ] # data after date
        then
            if [[ "$3" == "$4" ]]
            then
                echo "1"
                return
            fi
        fi
    fi

    echo "0"   
}

# Functions will increase number in arrays
add_one_to_ages() {
    if [ "$1" -lt "6" ]
    then
        (( ages[0]++ ))
    elif [ "$1" -lt  "16" ]
    then
        (( ages[1]++ ))
    elif [ "$1" -lt  "26" ]
    then
        (( ages[2]++ ))
    elif [ "$1" -lt  "36" ]
    then
        (( ages[3]++ ))
    elif [ "$1" -lt  "46" ]
    then
        (( ages[4]++ ))
    elif [ "$1" -lt  "56" ]
    then
        (( ages[5]++ ))
    elif [ "$1" -lt  "66" ]
    then
        (( ages[6]++ ))
    elif [ "$1" -lt  "76" ]
    then
        (( ages[7]++ ))
    elif [ "$1" -lt  "86" ]
    then
        (( ages[8]++ ))
    elif [ "$1" -lt  "96" ]
    then
        (( ages[9]++ ))
    elif [ "$1" -lt  "106" ]
    then
        (( ages[10]++ ))
    else
        (( ages[11]++ ))
    fi 
}
add_one_to_gender() {
    if [ "$1" == "M" ] 
    then
        (( genders[0]++ ))
    elif [ "$1" == "Z" ]
    then
        (( genders[1]++ ))
    else 
        (( genders[2]++ ))    
    fi 
}

# Count dates and compare them
count_days() {
    if [ "$date" == "" ]; then
        date=$(date +$1)
    fi

    if [ "$date" == "$1" ]; then
        count=$((count + 1))
    else
        echo "$date: $count"
        count=$((1))
        date=$(date +$1)
    fi
}
count_months() {
    if [ "$date" == "" ]; then
        date=$(date +$1)
        date=${date::-3} #delete last 3 chars
    else
        tmp_date=$(date +$1)
        tmp_date=${tmp_date::-3} #format $tmp_date

        if [ "$date" == "$tmp_date" ]; then
            count=$((count + 1))
        else
            echo "$date: $count"    
            count=$((1))
            date=$(date +$tmp_date)
        fi 
    fi
}
count_years() {
    if [ "$date" == "" ]; then
        date=$(date +$1)
        date=${date::-6} #delete last 6 chars
    else
        tmp_date=$(date +$1)
        tmp_date=${tmp_date::-6} #format $tmp_date

        if [ "$date" == "$tmp_date" ]; then
            count=$((count + 1))
        else
            echo "$date: $count"    
            count=$((1))
            date=$(date +$tmp_date)
        fi 
    fi
}

# Send data by date type
send_data_by_date_type() {
    if [ "$1" == "daily" ]; then
        count_days $2
    elif [ "$1" == "monthly" ]; then    
        count_months $2
    elif [ "$1" == "yearly" ]; then    
        count_years $2
    fi     
}

################################################
################# FUNCTIONS ####################
################################################

# Write help text to the terminal.
help() {
    printf "${RED}"
    echo "--------------------------------------------------"
    echo "|                                                |"
    echo "|       CORONA - POSITIVE USER ANALYZER          |"
    echo "|                                                |"
    echo "--------------------------------------------------"
    printf "${NOCOLOR}"
    echo "FORMAT:"
    echo "corona [-h] [FILTERS] [COMMAND] [LOG [LOG2 [...]]"
    echo "--------------------------------------------------"
    echo "MAIN:"
    echo "-h -> vypise pomocnik"
    echo "--------------------------------------------------"
    echo "FILTERS:"
    echo "-a DATETIME -> vypis zaznamov iba pod danom datume"
    echo "-b DATETIME -> vypis zaznamov iba pred danym datumom"
    echo "-g GENDER -> filter podla pohlavia (M = muzi, Z = zeny)"
    echo "-s [WIDTH] -> vypis dat graficky"
    echo "--------------------------------------------------"
    echo "COMMAND:"
    echo "infected -> spocita pocet nakazenych"
    echo "merge -> spoji subory so zaznamami do jedneho"
    echo "gender -> pocet nakazenych pre jednotlive pohlavia"
    echo "age -> statistika nakazenych podla veku"
    echo "daily -> statistika nakazenych pre jednotlive dni"
    echo "monthly -> statistika nakazenych pre jednotlive mesiace"
    echo "yearly -> statistika nakazenych pre jednotlive roky"
    echo "countries -> stastika nakazenych pre krajiny nakazy"
    echo "districts -> stastika nakazenych pre okresy"   
    echo "regions -> stastika nakazenych pre kraje"
    printf "${RED}"
    echo "--------------------------------------------------"
    printf "${NOCOLOR}"
}

# Print number of persons in table by filter. If input is get_num "x",
# return value is total number of all infected people. 
get_num() {
    declare -i num=-1
    declare -i actual_line=0    # This counter is for skipping first line
 
    while IFS=, read -r id datum vek pohlavi kraj_nuts_kod okres_lau_kod nakaza_v_zahranici nakaza_zeme_csu_kod reportovano_khs
    do
        actual_line=$((actual_line + 1))
        tmp_return_filter_a=`filter_a "$actual_line" "$1" "$datum" "$2"`    
        tmp_return_filter_b=`filter_b "$actual_line" "$1" "$datum" "$2"`    
        tmp_return_filter_g=`filter_g "$actual_line" "$1" "$pohlavi" "$2"`    

        if [ "$tmp_return_filter_a" == "1" ]; then
            num=$((num + 1))  
        elif [ "$tmp_return_filter_b" == "1" ]; then
            num=$((num + 1))  
        elif [ "$tmp_return_filter_g" == "1" ]; then
            num=$((num + 1))  
        else
            num=$((num + 1))  
        fi
    done < osoby.csv

    echo "$num"   
}

# Print number for each gender. If input is get_gender "x",
# return value is total number of all infected people sorted
# by gender. 
get_gender() {
    declare -i actual_line=0    # This counter is for skipping first line
 
    while IFS=, read -r id datum vek pohlavi kraj_nuts_kod okres_lau_kod nakaza_v_zahranici nakaza_zeme_csu_kod reportovano_khs
    do
        actual_line=$((actual_line + 1))
        tmp_return_filter_a=`filter_a "$actual_line" "$1" "$datum" "$2"`    
        tmp_return_filter_b=`filter_b "$actual_line" "$1" "$datum" "$2"`    
        tmp_return_filter_g=`filter_g "$actual_line" "$1" "$pohlavi" "$2"`    

        if [ "$tmp_return_filter_a" == "1" ]; then
            add_one_to_gender $pohlavi
        elif [ "$tmp_return_filter_b" == "1" ]; then
            add_one_to_gender $pohlavi
        elif [ "$tmp_return_filter_g" == "1" ]; then
            add_one_to_gender $pohlavi
        else
            add_one_to_gender $pohlavi
        fi    
    done < osoby.csv

    printf "M: ${genders[0]}\n" 
    printf "Z: ${genders[1]}\n" 
    printf "None: ${genders[2]}\n" 
}

# return value is total number of all infected people sorted by age. 
get_age() {
    declare -i actual_line=0    # This counter is for skipping first line

    while IFS=, read -r id datum vek pohlavi kraj_nuts_kod okres_lau_kod nakaza_v_zahranici nakaza_zeme_csu_kod reportovano_khs
    do
        actual_line=$((actual_line + 1))
        tmp_return_filter_a=`filter_a "$actual_line" "$1" "$datum" "$2"`    
        tmp_return_filter_b=`filter_b "$actual_line" "$1" "$datum" "$2"`    
        tmp_return_filter_g=`filter_g "$actual_line" "$1" "$pohlavi" "$2"`    

        if [ "$tmp_return_filter_a" == "1" ]; then
            add_one_to_ages $vek
        elif [ "$tmp_return_filter_b" == "1" ]; then
            add_one_to_ages $vek
        elif [ "$tmp_return_filter_g" == "1" ]; then
            add_one_to_ages $vek
        else
            add_one_to_ages $vek
        fi    
    done < osoby.csv

    printf  "0-5:\t ${ages[0]}\n" 
    printf  "6-15:\t ${ages[1]}\n"
    printf  "16-25:\t ${ages[2]}\n"
    printf  "26-35:\t ${ages[3]}\n"
    printf  "36-45:\t ${ages[4]}\n"
    printf  "46-55:\t ${ages[5]}\n"
    printf  "56-65:\t ${ages[6]}\n"
    printf  "66-75:\t ${ages[7]}\n"
    printf  "76-85:\t ${ages[8]}\n"
    printf  "86-95:\t ${ages[9]}\n"
    printf  "96-105:\t ${ages[10]}\n"
    printf  ">105:\t ${ages[11]}\n"
}

# Print number of persons in table by days/months/years filter. If input is get_num "x",
# return value is total number of all infected people. 
get_date() {
    declare -i actual_line=0    # This counter is for skipping first line

    while IFS=, read -r id datum vek pohlavi kraj_nuts_kod okres_lau_kod nakaza_v_zahranici nakaza_zeme_csu_kod reportovano_khs
    do
        actual_line=$((actual_line + 1))
        tmp_return_filter_a=`filter_a "$actual_line" "$1" "$datum" "$2"`    
        tmp_return_filter_b=`filter_b "$actual_line" "$1" "$datum" "$2"`    
        tmp_return_filter_g=`filter_g "$actual_line" "$1" "$pohlavi" "$2"`    

        if [ "$tmp_return_filter_a" == "1" ]; then
            send_data_by_date_type "$3" "$datum"   
        elif [ "$tmp_return_filter_b" == "1" ]; then
            send_data_by_date_type "$3" "$datum"
        elif [ "$tmp_return_filter_g" == "1" ]; then
            send_data_by_date_type "$3" "$datum"
        elif [ "$actual_line" != "1" ]; then
            send_data_by_date_type "$3" "$datum"
        fi    
    done < osoby.csv

    echo "$date: $count" # Print last line
}

################################################
################### MAIN #######################
################################################

export POSIXLY_CORRECT=yes

# Help (in this case just print help text and end program)
if  [ "$1" = "-h" ] ; then
    help

# Write infected people
elif [ "$1" = "infected" ] || [ "$3" == "infected" ]; then 
    if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" = "infected" ] # Filter is set
    then
        get_num "$1" "$2"   
    else
        get_num "x"
    fi    

# Write gender of infected people 
elif [ "$1" = "gender" ] || [ "$3" == "gender" ]; then 
    if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" = "gender" ] # Filter is set
    then
        get_gender "$1" "$2"   
    else
        get_gender "x"
    fi   

# Write age of infected people 
elif [ "$1" = "age" ] || [ "$3" == "age" ]; then 
    if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" = "age" ] # Filter is set
    then
        get_age "$1" "$2"   
    else
        get_age "x"
    fi

# Write infected people sorted by days
elif [ "$1" = "daily" ] || [ "$3" == "daily" ]; then 
    if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" = "daily" ] # Filter is set
    then
        get_date "$1" "$2" "daily"
    else
        get_date "x" "" "daily"
    fi

# Write infected people sorted by months
elif [ "$1" = "monthly" ] || [ "$3" == "monthly" ]; then 
    if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" = "monthly" ] # Filter is set
    then
        get_date "$1" "$2" "monthly"
    else
        get_date "x" "" "monthly"
    fi

# Write infected people sorted by years
elif [ "$1" = "yearly" ] || [ "$3" == "yearly" ]; then 
    if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" = "yearly" ] # Filter is set
    then
        get_date "$1" "$2" "yearly"
    else
        get_date "x" "" "yearly"
    fi

# todo: Wait for stdin
# elif [ "$1" = "" ]

# No command
else
    printf "Bol zadany nespravny tvar prikazu, pre napovedu napis ${RED}corona -h${NOCOLOR}\n"
fi

exit 0